"""s02a initial schema

Revision ID: 086db0070190
Revises: 
Create Date: 2026-09-27 12:49:18.716201
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '086db0070190'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('seq', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=True),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('published_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_events'))
    )
    op.create_index('ix_events_tenant_seq', 'events', ['tenant_id', 'seq'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_table('runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('idempotency_key', sa.Text(), nullable=False),
    sa.Column('idempotency_payload_sha256', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('total_budget_micros', sa.BigInteger(), nullable=False),
    sa.Column('reserved_micros', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('settled_micros', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('wall_clock_deadline', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('reserved_micros >= 0', name=op.f('ck_runs_reserved_nonneg')),
    sa.CheckConstraint('settled_micros >= 0', name=op.f('ck_runs_settled_nonneg')),
    sa.CheckConstraint('total_budget_micros >= 0', name=op.f('ck_runs_total_nonneg')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_runs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_runs')),
    sa.UniqueConstraint('tenant_id', 'idempotency_key', name='uq_runs_tenant_idem')
    )
    op.create_table('budget_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('attempt_id', sa.UUID(), nullable=True),
    sa.Column('entry_type', sa.Text(), nullable=False),
    sa.Column('amount_micros', sa.BigInteger(), nullable=False),
    sa.Column('idem_key', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('amount_micros >= 0', name=op.f('ck_budget_entries_amount_nonneg')),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_budget_entries_run_id_runs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_budget_entries')),
    sa.UniqueConstraint('run_id', 'idem_key', name='uq_budget_run_idem')
    )
    op.create_index('ix_budget_run_type', 'budget_entries', ['run_id', 'entry_type'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='3', nullable=False),
    sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['runs.id'], name=op.f('fk_jobs_run_id_runs')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_jobs_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs'))
    )
    op.create_index('ix_jobs_claim', 'jobs', ['status', 'created_at'], unique=False)
    op.create_table('attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Text(), nullable=False),
    sa.Column('lease_expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_attempts_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attempts')),
    sa.UniqueConstraint('job_id', 'attempt_no', name='uq_attempts_job_no')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attempts')
    op.drop_index('ix_jobs_claim', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('ix_budget_run_type', table_name='budget_entries')
    op.drop_table('budget_entries')
    op.drop_table('runs')
    op.drop_table('tenants')
    op.drop_index('ix_events_tenant_seq', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
