"""s02b api keys

Revision ID: 0d8471d9eb62
Revises: 086db0070190
Create Date: 2026-09-27 15:03:14.541211
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0d8471d9eb62'
down_revision: Union[str, None] = '086db0070190'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), server_default='tenant', nullable=False),
    sa.Column('token_hash', sa.Text(), nullable=False),
    sa.Column('token_prefix', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('tenant', 'admin')", name=op.f('ck_api_keys_role_valid')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_api_keys_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_api_keys')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_api_keys_token_hash'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('api_keys')
    # ### end Alembic commands ###
